name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  audit:
    strategy:
      matrix:
        os: [macos-15, macos-26]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false
      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-
      - name: Tap
        run: brew tap ${{ github.repository }}
      - name: Audit
        run: |
          brew audit ${{ github.repository }}/ffmpeg
          brew audit ${{ github.repository }}/mpv
  build:
    strategy:
      matrix:
        os: [macos-15, macos-26]
    runs-on: ${{ matrix.os }}

    needs: [audit]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false
      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-
      - name: Tap
        run: brew tap ${{ github.repository }}
      - name: Install ffmpeg
        run: |
          brew install --build-bottle ${{ github.repository }}/ffmpeg
          brew bottle --root-url https://github.com/${{ github.repository }}/releases/download/replaceheretoreleasename ${{ github.repository }}/ffmpeg
          ffmpeg -version
      - name: Upload ffmpeg bottle
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-bottle-${{ matrix.os }}
          path: "ffmpeg*.bottle.*"
      - name: Install mpv
        run: |
          brew install --build-bottle ${{ github.repository }}/mpv
          brew bottle --root-url https://github.com/${{ github.repository }}/releases/download/replaceheretoreleasename ${{ github.repository }}/mpv
          mpv --version
      - name: Upload mpv bottle
        uses: actions/upload-artifact@v4
        with:
          name: mpv-bottle-${{ matrix.os }}
          path: "mpv*.bottle.*"
      - name: Get commit date
        id: commit_date
        run: |
          echo "date=$(TZ=Asia/Tokyo git log -1 --format=%cd --date=format-local:'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.bottle.*"
          name: ${{ steps.commit_date.outputs.date }}
          tag_name: ${{ steps.commit_date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  install:
    strategy:
      matrix:
        os: [macos-15, macos-26]
    runs-on: ${{ matrix.os }}

    needs: [audit]

    steps:
      - name: Tap
        run: brew tap ${{ github.repository }}
      - name: Install ffmpeg
        run: |
          brew install ${{ github.repository }}/ffmpeg
          ffmpeg -version
      - name: Install mpv
        run: |
          brew install ${{ github.repository }}/mpv
          mpv --version
